# Generated by Django 4.1 on 2023-05-31 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_is_name_category_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_name',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='product.category'),
        ),
    ]
