# Generated by Django 4.1 on 2023-06-07 13:14

import autoslug.fields
from django.db import migrations
import src.apps.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_is_name_category_is_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=70, populate_from=src.apps.product.models.get_slug_value, slugify=src.apps.product.models.custom_slugify, unique=True),
        ),
    ]
